let suggestions = [
    "Akira Santhakumaran",
    "Audi AG",
    "Pomme",
    "Banane",
    "Orange",
    "Kiwi",
    "Ananas",
    "Fraise",
    "Poire",
    "Raisin",
    "Cerise",
    "Pêche",
    "Africain",
    "BMW (Bayerish Motoren Werke)",
    "Kitkat",
];
